---------70-463 Ch 1
USE [AdventureWorksDW2012]
GO

--EXEC sys.sp_tables

----------------Exclude non-additive measures
SELECT
	IST.TABLE_NAME AS [Table]
	, ISC.COLUMN_NAME AS [Column]
	, ISC.IS_NULLABLE AS [Allows nulls?]
	, ISC.DATA_TYPE AS [Type]
FROM INFORMATION_SCHEMA.TABLES IST
JOIN INFORMATION_SCHEMA.COLUMNS ISC
ON IST.TABLE_NAME = ISC.TABLE_NAME
WHERE
	IST.TABLE_NAME NOT LIKE '%sys%'
	--AND IST.TABLE_NAME <> 'dtproperties'
	AND IST.TABLE_SCHEMA <> 'INFORMATION_SCHEMA'
	AND IST.TABLE_NAME LIKE '%Fact%'
	AND (
	ISC.COLUMN_NAME NOT LIKE '%Calendar%'
	AND ISC.COLUMN_NAME NOT LIKE '%Date%'
	AND ISC.COLUMN_NAME NOT LIKE '%Desc%'
	AND ISC.COLUMN_NAME NOT LIKE '%Discount%'
	AND ISC.COLUMN_NAME NOT LIKE '%ID%'
	AND ISC.COLUMN_NAME NOT LIKE '%Key%'
	AND ISC.COLUMN_NAME NOT LIKE '%Name%'
	AND ISC.COLUMN_NAME NOT LIKE '%Number%'
	AND ISC.COLUMN_NAME NOT LIKE '%Price%'
	AND ISC.COLUMN_NAME NOT LIKE '%Shift%'
	AND ISC.COLUMN_NAME NOT LIKE '%Time%'
	AND ISC.COLUMN_NAME NOT LIKE '%Type%')
ORDER BY
	IST.TABLE_NAME
	, ISC.ORDINAL_POSITION